--INSERT INTO ingredients (ingredient_name, amount_mg_ml)
--VALUES
--    ('кофе', 1000),
--    ('вода', 6000),
--    ('молоко', 5000);
--
--INSERT INTO drinks (drink_name, drink_made_count)
--VALUES
--    ('эспрессо', 0),
--    ('американо', 0),
--    ('капучино', 0);
--
--INSERT INTO recipes (drink_id, ingredient_id, ingredient_amount)
--VALUES
--    (1, 1, 50),
--    (1, 2, 100),
--    (2, 1, 50),
--    (2, 2, 200),
--    (3, 1, 50),
--    (3, 3, 150);


